# Generated by Django 3.0.7 on 2020-06-07 04:29

from django.db import migrations, models
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='download.png', upload_to=userprofile.models.upload_location),
        ),
    ]
